# version: "3.9"

networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  avatar:
    image: avatar
    container_name: avatar
    build:
      context: .
      dockerfile: avatar/Dockerfile
    # volumes:
    #   - ./user_management:/workspace/user_management
    # depends_on:
    #   - db_user_management
    networks:
      - transcendence
    ports:
      - 8000:8000
    init: true
